# Generated by Django 5.1.7 on 2025-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
