# Generated by Django 5.1.7 on 2025-08-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customuser_matric_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='matric_number',
        ),
    ]
